vim.wo.number = true
vim.o.relativenumber = true
vim.o.clipboard = "unnamedplus" -- sync clipboard between os and nvim
vim.o.wrap = false
vim.o.linebreak = true
vim.o.autoindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shiftwidth = 4 -- number of spaces inserted for each identation
vim.o.tabstop = 4 -- insert n spaces for a tab
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.hlsearch = false
vim.o.splitbelow = true -- force all horizontal splits to go below current window
vim.o.splitright = true -- force all vertical splits to go to the right of current window
vim.o.smartindent = true -- make indenting smarter again
vim.o.showtabline = 2 -- always show tabs
vim.o.backspace = "indent,eol,start" -- allow backspace on
vim.o.pumheight = 10 -- pop up menu height
vim.o.conceallevel = 0 -- so that `` is visible in markdown files
vim.o.fileencoding = "utf-8" -- the encoding written to a file
vim.o.cmdheight = 1 -- more space in the neovim command line for displaying messages
vim.o.guicursor = "n-v-i-c:block-Cursor-blinkwait10-blinkon10-blinkoff10"
vim.opt.showmode = false
